# Generated by Django 3.1.7 on 2021-05-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taxPricce',
            new_name='taxPrice',
        ),
    ]
